// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		double num,ratio;
		int lowCounter = 0;
		int highCounter = 0;
		for (int i=0; i<n; i++)
		{
			num = Math.random();
			if (num > 0.5)
				highCounter++;
			else
				lowCounter++;
		}
		
		if (lowCounter==0) {
			System.out.println("> 0.5:	"+highCounter+" times");
			System.out.println("<= 0.5:	"+lowCounter+" times");
			return;
		}
		System.out.println("> 0.5:	"+highCounter+" times");
		System.out.println("<= 0.5:	"+lowCounter+" times");
		ratio = (double)highCounter/lowCounter;
		System.out.println("Ratio:	"+ratio);

	}
}
